# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikolai/lststools/ho5_imc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikolai/lststools/ho5_imc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolai/lststools/ho5_imc/CMakeFiles /home/nikolai/lststools/ho5_imc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolai/lststools/ho5_imc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ho5_imc

# Build rule for target.
ho5_imc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ho5_imc
.PHONY : ho5_imc

# fast build rule for target.
ho5_imc/fast:
	$(MAKE) -f CMakeFiles/ho5_imc.dir/build.make CMakeFiles/ho5_imc.dir/build
.PHONY : ho5_imc/fast

#=============================================================================
# Target rules for targets named imc

# Build rule for target.
imc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imc
.PHONY : imc

# fast build rule for target.
imc/fast:
	$(MAKE) -f CMakeFiles/imc.dir/build.make CMakeFiles/imc.dir/build
.PHONY : imc/fast

#=============================================================================
# Target rules for targets named udp

# Build rule for target.
udp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 udp
.PHONY : udp

# fast build rule for target.
udp/fast:
	$(MAKE) -f CMakeFiles/udp.dir/build.make CMakeFiles/udp.dir/build
.PHONY : udp/fast

IMC/Base/Factory.o: IMC/Base/Factory.cpp.o

.PHONY : IMC/Base/Factory.o

# target to build an object file
IMC/Base/Factory.cpp.o:
	$(MAKE) -f CMakeFiles/imc.dir/build.make CMakeFiles/imc.dir/IMC/Base/Factory.cpp.o
.PHONY : IMC/Base/Factory.cpp.o

IMC/Base/Factory.i: IMC/Base/Factory.cpp.i

.PHONY : IMC/Base/Factory.i

# target to preprocess a source file
IMC/Base/Factory.cpp.i:
	$(MAKE) -f CMakeFiles/imc.dir/build.make CMakeFiles/imc.dir/IMC/Base/Factory.cpp.i
.PHONY : IMC/Base/Factory.cpp.i

IMC/Base/Factory.s: IMC/Base/Factory.cpp.s

.PHONY : IMC/Base/Factory.s

# target to generate assembly for a file
IMC/Base/Factory.cpp.s:
	$(MAKE) -f CMakeFiles/imc.dir/build.make CMakeFiles/imc.dir/IMC/Base/Factory.cpp.s
.PHONY : IMC/Base/Factory.cpp.s

UDP/DatagramSocket.o: UDP/DatagramSocket.cpp.o

.PHONY : UDP/DatagramSocket.o

# target to build an object file
UDP/DatagramSocket.cpp.o:
	$(MAKE) -f CMakeFiles/udp.dir/build.make CMakeFiles/udp.dir/UDP/DatagramSocket.cpp.o
.PHONY : UDP/DatagramSocket.cpp.o

UDP/DatagramSocket.i: UDP/DatagramSocket.cpp.i

.PHONY : UDP/DatagramSocket.i

# target to preprocess a source file
UDP/DatagramSocket.cpp.i:
	$(MAKE) -f CMakeFiles/udp.dir/build.make CMakeFiles/udp.dir/UDP/DatagramSocket.cpp.i
.PHONY : UDP/DatagramSocket.cpp.i

UDP/DatagramSocket.s: UDP/DatagramSocket.cpp.s

.PHONY : UDP/DatagramSocket.s

# target to generate assembly for a file
UDP/DatagramSocket.cpp.s:
	$(MAKE) -f CMakeFiles/udp.dir/build.make CMakeFiles/udp.dir/UDP/DatagramSocket.cpp.s
.PHONY : UDP/DatagramSocket.cpp.s

ho5_imc.o: ho5_imc.cpp.o

.PHONY : ho5_imc.o

# target to build an object file
ho5_imc.cpp.o:
	$(MAKE) -f CMakeFiles/ho5_imc.dir/build.make CMakeFiles/ho5_imc.dir/ho5_imc.cpp.o
.PHONY : ho5_imc.cpp.o

ho5_imc.i: ho5_imc.cpp.i

.PHONY : ho5_imc.i

# target to preprocess a source file
ho5_imc.cpp.i:
	$(MAKE) -f CMakeFiles/ho5_imc.dir/build.make CMakeFiles/ho5_imc.dir/ho5_imc.cpp.i
.PHONY : ho5_imc.cpp.i

ho5_imc.s: ho5_imc.cpp.s

.PHONY : ho5_imc.s

# target to generate assembly for a file
ho5_imc.cpp.s:
	$(MAKE) -f CMakeFiles/ho5_imc.dir/build.make CMakeFiles/ho5_imc.dir/ho5_imc.cpp.s
.PHONY : ho5_imc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ho5_imc"
	@echo "... imc"
	@echo "... udp"
	@echo "... IMC/Base/Factory.o"
	@echo "... IMC/Base/Factory.i"
	@echo "... IMC/Base/Factory.s"
	@echo "... UDP/DatagramSocket.o"
	@echo "... UDP/DatagramSocket.i"
	@echo "... UDP/DatagramSocket.s"
	@echo "... ho5_imc.o"
	@echo "... ho5_imc.i"
	@echo "... ho5_imc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

